# name: Run eslint
# on: 
#   push:
#     branches: [main]
# jobs: 
#   build: 
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install Node.js
#         run: node --version
#       - name: Install Dependencies
#         run: npm install 
#       - name: Run ESLint
#         run: npx eslint
name: Run eslint
on: 
  push:
    branches: [main]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        run: node --version
      - name: Install Dependencies
        run: npm install 
      - name: Run ESLint
        run: npx eslint