name: eslint
on: 
  push:
    branches: [main]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - name: Install Node.js
        run: node --version 
      - name: Install npm
        run: npm --version
      - name: pwd
        run:  pwd
      - name: Run eslint
        run: npx eslint .
      