# # hello
# # key: value
# title: Website Name
# description: A website to upload a website
# age: 30
# #string, arrays, objects

# #array
# tags:
#   - technology
#   - images
#   - creative
# #indentation matters
# # spaces

# #objects
# address: 
#   street: MG Road
#   city: Banglore
#   state:  KA

# #Github actions
# # env variables
# value:  ${{ env.VALUE }}
# variable: ${{ github.VARIABLE_NAME }}

# Workflow ->
# When to run
# on -> when to trigger the workflow, on push to codebase, raising a pr to codebase

#How to run
# job - a task that can be run
# Define a series of steps inside a job to execute the workflow
# steps: a sequence of tasks or action that make up a job

name: projectX
on: 
  push:
    branches: [main]
jobs: 
  built: 
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
      - uses: actions/setup-node@v2
        with: 
          node-version: '14.x'
      - name: Print Node Version
        run: node -v